name: electrum_adapter
description: A Dart 3 client for ElectrumX servers with Firo support.  Forked from moontreeapp/electrum_adapter which was made for Ravencoin.
version: 3.0.0
homepage: https://github.com/cypherstack/electrum_adapter

environment:
  sdk: ^3.0.6

dependencies:
  async: ^2.9.0
  equatable: ^2.0.5
  json_rpc_2: ^3.0.2
  pedantic: ^1.11.1
  stream_channel: ^2.1.0
  stack_trace: ^1.10.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  timing: ^1.0.0

#dependency_overrides:
#  json_stream_parser:
#    path: ../../repos/dart-json-stream-decoder
